# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# Reference: https://www.appveyor.com/docs/appveyor-yml/

# Majority of this is taken from
# - https://dotnetcore.gaprogman.com/2017/06/08/continuous-integration-and-appveyor/
# - https://stefanscherer.github.io/setup-windows-docker-ci-appveyor/

version: 1.0.{build}

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Do not trigger two builds when pushing to a branch with an open pull request
skip_branch_with_pr: true

# Build worker image (VM template)
image: Ubuntu1804

configuration: Release

environment:
  DOCKER_USER:
    secure: DH/F3YmCTtoML7jh0N72CA==
  DOCKER_PASS:
    secure: Jgm/MYBo9+sIAc+HoJRk45+Fc2k36GCuLcS635Am9Sw=

init:
  - git config --global core.autocrlf true

before_build:
  # Display .NET Core version
  - dotnet --version
  # Display minimal restore text
  - dotnet restore --verbosity m

build_script:
  - cd src/Basket.Api
  - dotnet publish -c Release -o out Basket.Api.csproj
  - docker build -t jameslappin/basketapi .
  - cd ../..

test_script:
  - dotnet build src/Basket.Tests/Basket.Tests.csproj
  - dotnet test src/Basket.Tests/Basket.Tests.csproj

deploy_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push jameslappin/basketapi