# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# Reference: https://www.appveyor.com/docs/appveyor-yml/

version: 1.0.{build}

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Do not trigger two builds when pushing to a branch with an open pull request
skip_branch_with_pr: true

# Build worker image (VM template)
image: Visual Studio 2017

configuration: Release

build:
  verbosity: minimal