name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - edited
      - ready_for_review
  pull_request_review:
    types:
      - submitted
env:
  MERGE_LABELS: "auto-merge,!wip"
  MERGE_RETRY_SLEEP: 60000
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge-develop
        uses: "pascalgn/automerge-action@a4b03eff945989d41c623c2784d6602560b91e5b"
        if: github.base_ref == 'develop'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: pull-request-title
          MERGE_DELETE_BRANCH: "true"

      - name: automerge-master
        uses: "pascalgn/automerge-action@a4b03eff945989d41c623c2784d6602560b91e5b"
        if: github.base_ref == 'master'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: pull-request-title
