name: automerge
on:
  pull_request:
    branches: 
      - master
      - develop
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge-develop
        uses: "pascalgn/automerge-action@a4b03eff945989d41c623c2784d6602560b91e5b"
        if: github.base_ref == "develop"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"  
          MERGE_LABELS: "automerge,!wip"
          MERGE_COMMIT_MESSAGE: pull-request-title
          MERGE_DELETE_BRANCH: "true"

      - name: automerge-master
        uses: "pascalgn/automerge-action@a4b03eff945989d41c623c2784d6602560b91e5b"
        if: github.base_ref == "master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "merge"
          MERGE_LABELS: "automerge,!wip"
          MERGE_COMMIT_MESSAGE: pull-request-title
          
